train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: J://data_path/sr_datasets/Screen_Content_Image_Super-Resolution/Data/SCI1K-Train/HR
      repeat: 1
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled-fast
    args:
      inp_size: 48
      scale_max: 4
      scale_min: 1
      augment: True
  batch_size: 16

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: J://data_path/sr_datasets/Screen_Content_Image_Super-Resolution/Data/SCI1K-Test/X2/HR
      first_k: 10
      repeat: 16
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled-fast
    args:
      inp_size: 48
      scale_max: 4
      scale_min: 1
  batch_size: 8

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: sronet
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    width: 256
    blocks: 16

optimizer:
  name: adam
  args:
    lr: 4.e-5

epoch_max: 1000

warmup_step_lr:
  multiplier: 10
  total_epoch: 50

multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 100
eval_bsize: 16

resume: ~
pre_train: ~